package org.javaboy.vhr.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TestTableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_table
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_table
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_table
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated
     */
    public TestTableExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_table
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTestNameIsNull() {
            addCriterion("test_name is null");
            return (Criteria) this;
        }

        public Criteria andTestNameIsNotNull() {
            addCriterion("test_name is not null");
            return (Criteria) this;
        }

        public Criteria andTestNameEqualTo(String value) {
            addCriterion("test_name =", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameNotEqualTo(String value) {
            addCriterion("test_name <>", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameGreaterThan(String value) {
            addCriterion("test_name >", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameGreaterThanOrEqualTo(String value) {
            addCriterion("test_name >=", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameLessThan(String value) {
            addCriterion("test_name <", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameLessThanOrEqualTo(String value) {
            addCriterion("test_name <=", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameLike(String value) {
            addCriterion("test_name like", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameNotLike(String value) {
            addCriterion("test_name not like", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameIn(List<String> values) {
            addCriterion("test_name in", values, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameNotIn(List<String> values) {
            addCriterion("test_name not in", values, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameBetween(String value1, String value2) {
            addCriterion("test_name between", value1, value2, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameNotBetween(String value1, String value2) {
            addCriterion("test_name not between", value1, value2, "testName");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateIsNull() {
            addCriterion("test_birth_date is null");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateIsNotNull() {
            addCriterion("test_birth_date is not null");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateEqualTo(Date value) {
            addCriterionForJDBCDate("test_birth_date =", value, "testBirthDate");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("test_birth_date <>", value, "testBirthDate");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateGreaterThan(Date value) {
            addCriterionForJDBCDate("test_birth_date >", value, "testBirthDate");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("test_birth_date >=", value, "testBirthDate");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateLessThan(Date value) {
            addCriterionForJDBCDate("test_birth_date <", value, "testBirthDate");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("test_birth_date <=", value, "testBirthDate");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateIn(List<Date> values) {
            addCriterionForJDBCDate("test_birth_date in", values, "testBirthDate");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("test_birth_date not in", values, "testBirthDate");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("test_birth_date between", value1, value2, "testBirthDate");
            return (Criteria) this;
        }

        public Criteria andTestBirthDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("test_birth_date not between", value1, value2, "testBirthDate");
            return (Criteria) this;
        }

        public Criteria andTestAgeIsNull() {
            addCriterion("test_age is null");
            return (Criteria) this;
        }

        public Criteria andTestAgeIsNotNull() {
            addCriterion("test_age is not null");
            return (Criteria) this;
        }

        public Criteria andTestAgeEqualTo(Integer value) {
            addCriterion("test_age =", value, "testAge");
            return (Criteria) this;
        }

        public Criteria andTestAgeNotEqualTo(Integer value) {
            addCriterion("test_age <>", value, "testAge");
            return (Criteria) this;
        }

        public Criteria andTestAgeGreaterThan(Integer value) {
            addCriterion("test_age >", value, "testAge");
            return (Criteria) this;
        }

        public Criteria andTestAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_age >=", value, "testAge");
            return (Criteria) this;
        }

        public Criteria andTestAgeLessThan(Integer value) {
            addCriterion("test_age <", value, "testAge");
            return (Criteria) this;
        }

        public Criteria andTestAgeLessThanOrEqualTo(Integer value) {
            addCriterion("test_age <=", value, "testAge");
            return (Criteria) this;
        }

        public Criteria andTestAgeIn(List<Integer> values) {
            addCriterion("test_age in", values, "testAge");
            return (Criteria) this;
        }

        public Criteria andTestAgeNotIn(List<Integer> values) {
            addCriterion("test_age not in", values, "testAge");
            return (Criteria) this;
        }

        public Criteria andTestAgeBetween(Integer value1, Integer value2) {
            addCriterion("test_age between", value1, value2, "testAge");
            return (Criteria) this;
        }

        public Criteria andTestAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("test_age not between", value1, value2, "testAge");
            return (Criteria) this;
        }

        public Criteria andTestIdCardIsNull() {
            addCriterion("test_id_card is null");
            return (Criteria) this;
        }

        public Criteria andTestIdCardIsNotNull() {
            addCriterion("test_id_card is not null");
            return (Criteria) this;
        }

        public Criteria andTestIdCardEqualTo(String value) {
            addCriterion("test_id_card =", value, "testIdCard");
            return (Criteria) this;
        }

        public Criteria andTestIdCardNotEqualTo(String value) {
            addCriterion("test_id_card <>", value, "testIdCard");
            return (Criteria) this;
        }

        public Criteria andTestIdCardGreaterThan(String value) {
            addCriterion("test_id_card >", value, "testIdCard");
            return (Criteria) this;
        }

        public Criteria andTestIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("test_id_card >=", value, "testIdCard");
            return (Criteria) this;
        }

        public Criteria andTestIdCardLessThan(String value) {
            addCriterion("test_id_card <", value, "testIdCard");
            return (Criteria) this;
        }

        public Criteria andTestIdCardLessThanOrEqualTo(String value) {
            addCriterion("test_id_card <=", value, "testIdCard");
            return (Criteria) this;
        }

        public Criteria andTestIdCardLike(String value) {
            addCriterion("test_id_card like", value, "testIdCard");
            return (Criteria) this;
        }

        public Criteria andTestIdCardNotLike(String value) {
            addCriterion("test_id_card not like", value, "testIdCard");
            return (Criteria) this;
        }

        public Criteria andTestIdCardIn(List<String> values) {
            addCriterion("test_id_card in", values, "testIdCard");
            return (Criteria) this;
        }

        public Criteria andTestIdCardNotIn(List<String> values) {
            addCriterion("test_id_card not in", values, "testIdCard");
            return (Criteria) this;
        }

        public Criteria andTestIdCardBetween(String value1, String value2) {
            addCriterion("test_id_card between", value1, value2, "testIdCard");
            return (Criteria) this;
        }

        public Criteria andTestIdCardNotBetween(String value1, String value2) {
            addCriterion("test_id_card not between", value1, value2, "testIdCard");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_table
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_table
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}