package org.javaboy.vhr.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table test_table
 */
public class TestTable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   测试姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.test_name
     *
     * @mbg.generated
     */
    private String testName;

    /**
     * Database Column Remarks:
     *   测试出生日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.test_birth_date
     *
     * @mbg.generated
     */
    private Date testBirthDate;

    /**
     * Database Column Remarks:
     *   测试年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.test_age
     *
     * @mbg.generated
     */
    private Integer testAge;

    /**
     * Database Column Remarks:
     *   测试身份证号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.test_id_card
     *
     * @mbg.generated
     */
    private String testIdCard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.id
     *
     * @return the value of test_table.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.id
     *
     * @param id the value for test_table.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.test_name
     *
     * @return the value of test_table.test_name
     *
     * @mbg.generated
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.test_name
     *
     * @param testName the value for test_table.test_name
     *
     * @mbg.generated
     */
    public void setTestName(String testName) {
        this.testName = testName == null ? null : testName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.test_birth_date
     *
     * @return the value of test_table.test_birth_date
     *
     * @mbg.generated
     */
    public Date getTestBirthDate() {
        return testBirthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.test_birth_date
     *
     * @param testBirthDate the value for test_table.test_birth_date
     *
     * @mbg.generated
     */
    public void setTestBirthDate(Date testBirthDate) {
        this.testBirthDate = testBirthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.test_age
     *
     * @return the value of test_table.test_age
     *
     * @mbg.generated
     */
    public Integer getTestAge() {
        return testAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.test_age
     *
     * @param testAge the value for test_table.test_age
     *
     * @mbg.generated
     */
    public void setTestAge(Integer testAge) {
        this.testAge = testAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.test_id_card
     *
     * @return the value of test_table.test_id_card
     *
     * @mbg.generated
     */
    public String getTestIdCard() {
        return testIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.test_id_card
     *
     * @param testIdCard the value for test_table.test_id_card
     *
     * @mbg.generated
     */
    public void setTestIdCard(String testIdCard) {
        this.testIdCard = testIdCard == null ? null : testIdCard.trim();
    }
}